[package]
name = "sensitive-rs"
description = "Sensitive word search, verification, filtering and replacement."
version = "0.3.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["houseme <housemecn@gmail.com>"]
repository = "https://github.com/houseme/sensitive-rs"
homepage = "https://houseme.github.io/sensitive-rs"
documentation = "https://docs.rs/sensitive-rs"
keywords = ["sensitive", "generate", "filter", "trie", "replace-verification"]
categories = ["memory-management", "encoding", "science", "algorithms"]
readme = "README.md"
# Crate build related
exclude = ["tests/*", ".gitignore"]
include = ["src/**", "dict/**", "Cargo.toml", "README.md", "README_CN.md", "LICENSE-APACHE", "LICENSE-MIT", "CHANGELOG.md"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
opt-level = 3
debug = false
lto = true     # optimize when linking
codegen-units = 1  # Reduce code generation units to improve optimization

[dependencies]
regex = "1.11.1"
reqwest = { version = "0.12.22", default-features = false, features = ["rustls-tls", "charset", "http2", "macos-system-configuration", "blocking"], optional = true }

[features]
default = []
net = ["dep:reqwest"]
