max_width = 120
use_small_heuristics = "Max"
use_field_init_shorthand = true
reorder_imports = true
edition = "2021"
newline_style = "Unix"
hard_tabs = false
tab_spaces = 4
reorder_modules = true
remove_nested_parens = true
merge_derives = true
use_try_shorthand = false
force_explicit_abi = true